version: "3.8"
services:
  mysql:
    image: mysql:8.0.31
    container_name: library_mysql
    environment:
      MYSQL_DATABASE: library
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: library-app
    container_name: library_app
    build:
      context: ..
      dockerfile: ../Dockerfile
    environment:
      DB_URL: jdbc:mysql://mysql:3306/library?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - "8082:8082"
    depends_on:
      - mysql

volumes:
  mysql-data:
    driver: local
